spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nicexy/ConfigServer
          username: nicexy
          password: nicepro666
server:
  port: 12581


